### ISSUE TITLE
How to execute "manage.py" commands?

### ISSUE THREAD

**Issue by ghost** [armadillica/pillar#4]
Has `manage.py` been removed? The documentation asks for `manage.py` commands, but it isn't in the latest version anymore that I know of; after searching for the file I have only been able to find it in much earlier versions. (I am also aware that the documentation is a work-in-progress.)

Is there a command or set of commands that replaces what `manage.py` did, that I can use to set up users and projects? Or would I be able to recover the latest `manage.py` and use that?

**Comment by sybrenstuvel** [comment]
We could bring `manage.py` back to the Pillar repository. For now, you can grab it from the [Blender Cloud repo](https://developer.blender.org/diffusion/BC/), which is where we moved it to. Note that it imports `runserver.py`, which is specific to Blender Cloud -- you will probably be using other Pillar extensions. This is also why we moved the file in the first place -- it should load the extensions used by your project and make them all available to you, rather than only the core Pillar CLI commands.
